export const EVENTOS_LIST_REQUEST = 'EVENTOS_LIST_REQUEST';
export const EVENTOS_LIST_SUCCESS = 'EVENTOS_LIST_SUCCESS';
export const EVENTOS_LIST_FAIL = 'EVENTOS_LIST_FAIL';

export const EVENTOS_DETAILS_REQUEST = 'EVENTOS_DETAILS_REQUEST';
export const EVENTOS_DETAILS_SUCCESS = 'EVENTOS_DETAILS_SUCCESS';
export const EVENTOS_DETAILS_FAIL = 'EVENTOS_DETAILS_FAIL';

export const EVENTOS_CREATE_REQUEST = 'EVENTOS_CREATE_REQUEST';
export const EVENTOS_CREATE_SUCCESS = 'EVENTOS_CREATE_SUCCESS';
export const EVENTOS_CREATE_FAIL = 'EVENTOS_CREATE_FAIL';
export const EVENTOS_CREATE_RESET = 'EVENTOS_CREATE_RESET';

export const EVENTOS_REVIEW_CREATE_REQUEST = 'EVENTOS_REVIEW_CREATE_REQUEST';
export const EVENTOS_REVIEW_CREATE_SUCCESS = 'EVENTOS_REVIEW_CREATE_SUCCESS';
export const EVENTOS_REVIEW_CREATE_FAIL = 'EVENTOS_REVIEW_CREATE_FAIL';
export const EVENTOS_REVIEW_CREATE_RESET = 'EVENTOS_REVIEW_CREATE_RESET';

export const EVENTOS_UPDATE_REQUEST = 'EVENTOS_UPDATE_REQUEST';
export const EVENTOS_UPDATE_SUCCESS = 'EVENTOS_UPDATE_SUCCESS';
export const EVENTOS_UPDATE_FAIL = 'EVENTOS_UPDATE_FAIL';
export const EVENTOS_UPDATE_RESET = 'EVENTOS_UPDATE_RESET';

export const EVENTOS_DELETE_REQUEST = 'EVENTOS_DELETE_REQUEST';
export const EVENTOS_DELETE_SUCCESS = 'EVENTOS_DELETE_SUCCESS';
export const EVENTOS_DELETE_FAIL = 'EVENTOS_DELETE_FAIL';
export const EVENTOS_DELETE_RESET = 'EVENTOS_DELETE_RESET';

export const EVENTOS_CATEGORY_LIST_REQUEST = 'EVENTOS_CATEGORY_LIST_REQUEST';
export const EVENTOS_CATEGORY_LIST_SUCCESS = 'EVENTOS_CATEGORY_LIST_SUCCESS';
export const EVENTOS_CATEGORY_LIST_FAIL = 'EVENTOS_CATEGORY_LIST_FAIL';
